### DISCUSSION TITLE
Enable HTTPS service in trame

### DISCUSSION THREAD

**Discussion by Jimmy-KL** [Kitware/trame#153] [Q&A] [answered]
We are using HTTPS in our project. Is it possible to change the web service of trame from HTTP to HTTPS and how to do it? Thanks!

**Comment by jourdain** [comment, marked as answer]
You can put the docker service behind nginx or else. Otherwise, you can also use [the `--ssl` arg](https://github.com/Kitware/wslink/blob/master/python/src/wslink/server.py#L104-L110)

**Reply by timeanddoctor** [reply]
python trametst.py  --ssl ('./https/localhost+3.pem','./https/localhost+3-key.pem')  

I test with the upper code but not working

**Reply by timeanddoctor** [reply]
```
import http.server
import ssl

httpd = http.server.HTTPServer(('192.168.10.10', 1234), http.server.SimpleHTTPRequestHandler)
httpd.socket = ssl.wrap_socket(httpd.socket, certfile='./localhost+3.pem', keyfile='./localhost+3-key.pem', server_side=True, ssl_version=ssl.PROTOCOL_TLSv1_2)
httpd.serve_forever()
```

this can work for me

**Reply by jourdain** [reply]
In general, you don't want to expose your trame process directly but since I don't know what you are trying to do, I can't really help. 

Also as you can see you are not following the [documentation](https://github.com/Kitware/wslink/blob/master/python/src/wslink/server.py#L109)

You should have wrote `python trametst.py --ssl "./https/localhost+3.pem,./https/localhost+3-key.pem"`

**Reply by tayran-mila** [reply]
Hello everyone,

I am currently working on enabling the HTTPS service in my application as well, but I'm encountering some issues.

My application is essentially running based on the trame cookie cutter example and it is hosted remotely. I've created two certificate files and placed them inside my trame environment using a Dockerfile, with the file paths '/.ssl/certificate.pem' and '/.ssl/key.pem'.

Following Sebastien's suggestion, I have made the necessary configurations in the apps.yml file:

````
trame: # Default app under /index.html
  cmd:
    - /opt/paraview/bin/pvpython
    - -m
    - paraview.apps.trame
    - --trame-app
    - dashboard
    - --data
    - /data
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --ssl
    - '/.ssl/certificate.pem,/.ssl/key.pem'
    - --server
dashboard: # /dashboard.html
  cmd:
    - /opt/paraview/bin/pvpython
    - -m
    - paraview.apps.trame
    - --trame-app
    - dashboard
    - --data
    - ${data} # <-- come from url(data=...)
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --ssl
    - '/.ssl/certificate.pem,/.ssl/key.pem'
    - --server
````

However, it is not working. Do you have any suggestions for resolving this issue?
