### DISCUSSION TITLE
Where should users open an issue?

### DISCUSSION THREAD

**Discussion by banesullivan** [Kitware/trame#200] [General]
If I encounter a bug with `trame-vtk`, should I report it in this repository or in `trame-vtk`'s repository. Similarly for any of the submodules.

If the answer is here, then we may want to use an Issue template that forces users to open the issue here. This can be done with `.github/ISSUE_TEMPLATE/config.yml` in each of the submodule repos:

```yaml
# Documentation for this file can be found at:
# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository

blank_issues_enabled: true  # this should still be present for developers
contact_links:
  - name: "Open a Trame issue"
    url: https://github.com/Kitware/trame/issues/new
    about: We use the main Trame repository to track issues, please open there

```
