### DISCUSSION TITLE
How to make trame docker serve https/wss directly?

### DISCUSSION THREAD

**Discussion by tayran-mila** [Kitware/trame#334] [General] [answered]
Hello everyone!

I am currently working on enabling the HTTPS service in my application, but I'm encountering some issues.

My application is essentially running based on the trame cookie cutter example and it is hosted remotely. I've created two certificate files and placed them inside my trame environment using a Dockerfile, with the file paths '/etc/ssl/certs/trame.crt' and '/etc/ssl/private/trame.key'.

Following Sebastien's suggestion in another thread, I have made the necessary configurations in the apps.yml file:

```
trame: # Default app under /index.html
  cmd:
    - /opt/paraview/bin/pvpython
    - -m
    - paraview.apps.trame
    - --trame-app
    - dashboard
    - --data
    - /data
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --ssl
    - '/etc/ssl/certs/trame.crt,/etc/ssl/private/trame.key'
    - --server
dashboard: # /dashboard.html
  cmd:
    - /opt/paraview/bin/pvpython
    - -m
    - paraview.apps.trame
    - --trame-app
    - dashboard
    - --data
    - ${data} # <-- come from url(data=...)
    - --host
    - ${host}
    - --port
    - ${port}
    - --authKey
    - ${secret}
    - --ssl
    - '/etc/ssl/certs/trame.crt,/etc/ssl/private/trame.key'
    - --server
```

Then I updated the Apache configuration file '/etc/apache2/sites-available/default-ssl.conf' within docker to contain the path to the files (though I am not sure if this is the file I should have modified):
```
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/html

                # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
                # error, crit, alert, emerg.
                # It is also possible to configure the loglevel for particular
                # modules, e.g.
                #LogLevel info ssl:warn

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                # For most configuration files from conf-available/, which are
                # enabled or disabled at a global level, it is possible to
                # include a line for only one particular virtual host. For example the
                # following line enables the CGI configuration for this host only
                # after it has been globally disabled with "a2disconf".
                #Include conf-available/serve-cgi-bin.conf

                #   SSL Engine Switch:
                #   Enable/Disable SSL for this virtual host.
                SSLEngine on

                #   A self-signed (snakeoil) certificate can be created by installing
                #   the ssl-cert package. See
                #   /usr/share/doc/apache2/README.Debian.gz for more info.
                #   If both key and certificate are stored in the same file, only the
                #   SSLCertificateFile directive is needed.
                SSLCertificateFile /etc/ssl/certs/trame.crt
                SSLCertificateKeyFile /etc/ssl/private/trame.key

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>

        </VirtualHost>
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Finally, I built the image and ran the run_image.sh as:

```
#!/usr/bin/env bash


echo "$HOME/dashboard/data"

docker run -it --rm \
    -p 8081:443 \
    --network=postgres-network \
    -v "$HOME:/work" \
    dashboard_dev
```

It is still not working and the docker logs are not helping. Would you happen to have any idea what I am doing wrong?
