### DISCUSSION TITLE
Use Custom interactor in Docker

### DISCUSSION THREAD

**Discussion by matsc087** [Kitware/trame#696] [Trame/VTK]
Hi im trying to use a custom interactor. I found another [thread](https://github.com/Kitware/trame/discussions/244) that said to switch from vtk.vtkLocalView to vtk.vtkRemoteView but when i do that i run into this error (Im hosting in docker) trame-app _exited with code 139_
But it does not crash until I enter and view the site.

May be worth adding that if run this in a local python virual enviorment without docker, The application does not load in icons and eventually just slowsdown/crashes and is non responsive. Which makes me think it may not be dockers fault?

Here is my Dockerfile
``` dockerfile
# Use Python runtime as the base image
FROM python:3.11-bookworm

# Set the working directory
WORKDIR /app
RUN apt-get update && apt-get -y install libglfw3-dev libgles2-mesa-dev
COPY requirements.txt .

# Install dependencies
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Copy everything in current directory to container
COPY . .

# Expose the port
EXPOSE 1234

# Uncomment if -it command does not work
# ENV PYTHONUNBUFFERED=1

# Run the application
CMD ["python", "src/main.py", "--server","--port", "1234", "--host", "0.0.0.0"]
```

and docker-compose.yml

``` yml
services:
  trame-app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64  # Mac fix :) 
    container_name: trame-app
    # seems to not be needed ¯\_(ツ)_/¯
    #volumes:
    #  - .:/app  # mount to docker container 
    ports:
      - "1234:1234"
    stdin_open: true  # -i 
    tty: true         # -t
    develop:
      watch:
        - path: ./
          target: /app
          action: sync+restart
```

VTK part:

``` Python
renderer : vtkRenderer = vtkRenderer()

renderWindow : vtkRenderWindow = vtkRenderWindow()
renderWindow.AddRenderer(renderer)

def DummyFunc2(obj, ev):
    print('After Event')
    
interactorStyle : MyInteractorStyle = MyInteractorStyle()
# TODO Replace with custom interactor style
renderWindowInteractor : vtkRenderWindowInteractor = vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)

style = vtkInteractorStyleTrackballCamera()
style.AddObserver('RightButtonPressEvent', DummyFunc2, -1.0)
renderWindowInteractor.SetInteractorStyle(style)
renderWindowInteractor.Initialize()


# Heart Valve, Later populated with STL file in load_file()
readerSTL : vtkSTLReader = vtkSTLReader()
mapper : vtkPolyDataMapper = vtkPolyDataMapper()
cone_source = vtkConeSource()
mapper.SetInputConnection(cone_source.GetOutputPort())
actor = vtkActor()
actor.SetMapper(mapper)
renderer.AddActor(actor)

valve : vtkActor = vtkActor()
renderer.AddActor(valve)
renderer.ResetCamera()


# -----------------------------------------------------------------------------
# Trame setup
# -----------------------------------------------------------------------------

server : Server = get_server(client_type = "vue2")
state : State = server.state
ctrl : Controller = server.controller
```

Here is the GUI part:
```Python

with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("viewer")

    # Main content
    with layout.content:
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            view = vtk.VtkRemoteView(renderWindow)
            ctrl.view_update = view.update
            ctrl.view_reset_camera = view.reset_camera
            ctrl.upload_ct = upload_ct
            ctrl.export = export

```
